name: Tag New Version and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-and-release:
    uses: George-Ogden/actions/.github/workflows/python-release.yaml@v4.2.0
    with:
      validation-code: "from extra_types.types import Nat; from extra_types.type_utils import strict_cast; strict_cast(Nat, 0)"
